version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: portalops
      POSTGRES_USER: portalops
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../database/sample_data.sql:/docker-entrypoint-initdb.d/02-sample_data.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portalops -d portalops"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://portalops:password@db:5432/portalops
      JWT_SECRET_KEY: your-super-secret-jwt-key-change-this-in-production
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 15
      API_V1_STR: /api
      PROJECT_NAME: PortalOps
      UPLOAD_DIR: /uploads
      MAX_FILE_SIZE: 10485760
      HR_WEBHOOK_API_KEY: your-hr-webhook-secret-key
      DEBUG: "false"
    volumes:
      - uploads_data:/uploads
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  uploads_data:



